/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Contact = IDL.Record({
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Nat64,
  'phone' : IDL.Text,
});
export const Location = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getCafeInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'name' : IDL.Text,
          'whatsapp' : IDL.Text,
          'phone' : IDL.Text,
          'location' : Location,
        }),
      ],
      ['query'],
    ),
  'getContact' : IDL.Func([IDL.Principal], [Contact], ['query']),
  'isContacted' : IDL.Func([], [IDL.Bool], ['query']),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Nat64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Contact = IDL.Record({
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Nat64,
    'phone' : IDL.Text,
  });
  const Location = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  
  return IDL.Service({
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getCafeInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'name' : IDL.Text,
            'whatsapp' : IDL.Text,
            'phone' : IDL.Text,
            'location' : Location,
          }),
        ],
        ['query'],
      ),
    'getContact' : IDL.Func([IDL.Principal], [Contact], ['query']),
    'isContacted' : IDL.Func([], [IDL.Bool], ['query']),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat64],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };